CREATE TABLE public.ft_455 (
  sk_tempo integer NULL,
  sk_cliente_pagador integer NULL,
  sk_cliente_destinatario integer NULL,
  sk_cliente_expedidor integer NULL,
  sk_cliente_recebedor integer NULL,
  vlr_frete numeric NULL,
  qtd_volumes numeric NULL,
  vlr_mercadoria numeric NULL,
  sk_tempo_autorizacao integer NULL,
  sk_tempo_ult_ocor integer NULL,
  sk_tempo_prev_entrega integer NULL,
  sk_tempo_entrega integer NULL,
  sk_tempo_inc_fatura integer NULL,
  sk_und_emis integer NULL,
  sk_und_recept integer NULL,
  vlr_ctrc_origem numeric NULL,
  peso_calculado numeric NULL,
  ano_mes character varying(20) NULL,
  sk_dim_frete bigint NULL,
  anomes character varying(10) NULL,
  vlr_frete2 numeric NULL,
  "Valor do Frete sem ICMS" numeric NULL,
  "Base de Calculo" numeric NULL,
  "Valor do ICMS" numeric NULL,
  "Aliquota" text NULL,
  "Valor do ISS" numeric NULL,
  "CAT" numeric NULL,
  "ITR" numeric NULL,
  "GRIS" numeric NULL,
  "Pedagio" numeric NULL,
  "TAS" numeric NULL,
  "TDA" numeric NULL,
  "TDC" numeric NULL,
  "TDE" numeric NULL,
  "TRT" numeric NULL,
  "POS" numeric NULL,
  "Frete Peso" numeric NULL,
  "Frete Valor" numeric NULL,
  "Valor do ICMS origem" numeric NULL,
  "Valor da Comissao de Expedicao" numeric NULL,
  "Rel de Comissao de Expedicao" text NULL,
  "Valor da Comissao Exp Creditada" numeric NULL,
  "Valor da Comissao de Recepcao" numeric NULL,
  "Rel de Comissao de Recepcao" text NULL,
  "Valor da Comissao Rec Creditada" numeric NULL,
  "Valor da Fatura" numeric NULL,
  "Valor Liquidacao Fatura" numeric NULL,
  sk_ft_455 bigserial NOT NULL
);

ALTER TABLE public.ft_455
ADD CONSTRAINT ft_455_pk PRIMARY KEY (sk_ft_455)
